#!/bin/bash
echo "Enter your C file name..."
read file_name
echo "Creating $file_name.c !"
touch $file_name.c
echo -e "#include<stdio.h>\n#include\"main.h\"\n/**\n *\n *\n *\n */\n{\n\n\n\n\n\n\n\n\treturn(0);\n}" >> $file_name.c
vi $file_name.c
